name: Deploy
on: [push, pull_request]

jobs:
  vercel-deploy:
    name: Vercel Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Install Vercel CLI
        run: |
          npm install --global vercel@latest

      - name: Build
        run: |
          pnpm install
          pnpm build

      - name: Deploy
        run: |
          vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
